@class BBAttachments, BBSectionIcon, NSMutableSet, BBSound, BBContent, NSArray, NSTimeZone, NSDictionary, NSDate, NSSet, NSString, NSMutableDictionary, NSMutableArray, BBAction;

@interface BBBulletin : NSObject <NSCopying, NSCoding> {
    BOOL _hasEventDate;
    BOOL _dateIsAllDay;
    BOOL _clearable;
    BOOL _wantsFullscreenPresentation;
    BOOL _expiresOnPublisherDeath;
    BOOL _showsMessagePreview;
    BOOL _usesExternalSync;
    NSString *_sectionID;
    NSSet *_subsectionIDs;
    NSString *_publisherRecordID;
    NSString *_publisherBulletinID;
    NSString *_dismissalID;
    int _addressBookRecordID;
    int _sectionSubtype;
    BBContent *_content;
    BBContent *_modalAlertContent;
    BBContent *_starkBannerContent;
    NSDate *_date;
    NSDate *_endDate;
    NSDate *_recencyDate;
    int _dateFormatStyle;
    NSTimeZone *_timeZone;
    unsigned int _accessoryStyle;
    BBSound *_sound;
    BBAttachments *_attachments;
    NSString *_unlockActionLabelOverride;
    NSMutableDictionary *_actions;
    NSArray *_buttons;
    NSDictionary *_context;
    NSDate *_expirationDate;
    unsigned int _expirationEvents;
    NSSet *_alertSuppressionContexts;
    NSString *_bulletinID;
    NSDate *_lastInterruptDate;
    NSDate *_publicationDate;
    NSString *_bulletinVersionID;
    NSMutableArray *_lifeAssertions;
    NSMutableSet *_observers;
    unsigned int realertCount_deprecated;
    NSSet *alertSuppressionAppIDs_deprecated;
}

@property(readonly) NSString * sectionDisplayName;
@property(readonly) BBSectionIcon * sectionIcon;
@property(readonly) BOOL sectionDisplaysCriticalBulletins;
@property(readonly) BOOL showsSubtitle;
@property(readonly) unsigned int messageNumberOfLines;
@property(readonly) BOOL usesVariableLayout;
@property(readonly) BOOL orderSectionUsingRecencyDate;
@property(readonly) BOOL showsDateInFloatingLockScreenAlert;
@property(readonly) NSString * topic;
@property(readonly) NSString * missedBannerDescriptionFormat;
@property(readonly) NSString * fullUnlockActionLabel;
@property(readonly) NSString * unlockActionLabel;
@property(readonly) NSSet * alertSuppressionAppIDs;
@property(readonly) BOOL coalescesWhenLocked;
@property(readonly) BOOL suppressesMessageForPrivacy;
@property(readonly) unsigned int realertCount;
@property(readonly) BOOL inertWhenLocked;
@property(readonly) BOOL preservesUnlockActionCase;
@property(readonly) BOOL bannerShowsSubtitle;
@property(readonly) BOOL visuallyIndicatesWhenDateIsInFuture;
@property(readonly) unsigned int subtypePriority;
@property(readonly) int iPodOutAlertType;
@property(copy) NSString * bulletinID;
@property(copy) NSString * section;
@property(copy) NSString * sectionID;
@property(copy) NSSet * subsectionIDs;
@property(copy) NSString * recordID;
@property(copy) NSString * publisherBulletinID;
@property(copy) NSString * dismissalID;
@property int addressBookRecordID;
@property int sectionSubtype;
@property(copy) NSString * title;
@property(copy) NSString * subtitle;
@property(copy) NSString * message;
@property(retain) BBContent * modalAlertContent;
@property(retain) BBContent * starkBannerContent;
@property BOOL hasEventDate;
@property(retain) NSDate * date;
@property(retain) NSDate * endDate;
@property(retain) NSDate * recencyDate;
@property int dateFormatStyle;
@property BOOL dateIsAllDay;
@property(retain) NSTimeZone * timeZone;
@property unsigned int accessoryStyle;
@property BOOL clearable;
@property(retain) BBSound * sound;
@property(readonly) int primaryAttachmentType;
@property BOOL wantsFullscreenPresentation;
@property(copy) BBAction * defaultAction;
@property(copy) BBAction * alternateAction;
@property(copy) BBAction * acknowledgeAction;
@property(copy) BBAction * snoozeAction;
@property(copy) NSArray * buttons;
@property(copy) NSSet * alertSuppressionContexts;
@property BOOL expiresOnPublisherDeath;
@property(retain) NSDictionary * context;
@property(retain) NSDate * lastInterruptDate;
@property(retain) NSDate * publicationDate;
@property BOOL usesExternalSync;
@property(retain) BBContent * content;
@property(retain) BBAttachments * attachments;
@property(copy) NSString * unlockActionLabelOverride;
@property(retain) NSMutableDictionary * actions;
@property BOOL showsMessagePreview;
@property(copy) NSString * bulletinVersionID;
@property(retain) NSDate * expirationDate;
@property unsigned int expirationEvents;
@property(copy) BBAction * expireAction;
@property unsigned int realertCount_deprecated;
@property(copy) NSSet * alertSuppressionAppIDs_deprecated;
@property(retain) NSMutableSet * observers;
@property(retain) NSMutableArray * lifeAssertions;

@end